/** نصوص الواجهة والأخطاء بالعربية */
export const ar = {
  appName: "المنزّل",
  appTagline: "فيديو · صوت · صور",
  heroTitle: "نزّل",
  heroLine2: "من أي منصة",
  heroSub: "الصق الرابط. اختر الجودة. حمّل.",

  pastePlaceholder: "الصق الرابط هنا…",
  paste: "لصق",
  analyze: "تحليل",

  video: "فيديو",
  audio: "صوت",
  image: "صورة",
  chooseQuality: "الجودة",

  downloadVideo: "تحميل الفيديو",
  downloadAudio: "تحميل الصوت",
  downloadImage: "تحميل الصورة",
  downloadingProgress: "جاري التحميل",
  cancelDownload: "إلغاء التحميل",
  downloadCancelled: "تم إلغاء التحميل",
  githubStar: "أعطِ المشروع نجمة على GitHub",
  rateLimited: "طلبات كثيرة — انتظر قليلاً ثم حاول مجدداً",
  requestTooLarge: "الطلب كبير جداً",
  invalidExtension: "صيغة الملف غير مدعومة",

  engineInitializing: "جاري تجهيز المحرك — انتظر دقيقة ثم حدّث الصفحة",
  engineNotReady: "المحرك غير جاهز — انتظر قليلاً أو حدّث الصفحة",
  ready: "متصل",
  noPreview: "بدون معاينة",

  networkError: "خطأ في الشبكة. حاول مرة أخرى.",
  downloadFailed: "فشل التحميل",
  imageDownloadFailed: "فشل تحميل الصورة. جرّب دقة أخرى.",
  notDirectImage: "هذا ليس رابط صورة مباشرة — اختر فيديو أو صوت.",
  videoDownloadFailed: "فشل التحميل. جرّب جودة أخرى.",

  footer: "للاستخدام الشخصي · احترم حقوق النشر",
  version: "1.0.00",
  madeWithLove: "صُنع بحب ❤️",
  author: "عبدالرحمن المحمد",
  authorInstagram: "@AbdAlm10 على إنستغرام",
  platformsCount: "1000+ منصة",
  result: "الملف جاهز",
  engineLoading: "يتصل…",

  urlTooShort: "الرابط قصير جداً",
  urlTooLong: "الرابط طويل جداً",
  urlInvalid: "أدخل رابطاً صالحاً (http أو https)",
  formatIdInvalid: "معرّف الصيغة غير صالح",
  urlOrDirectRequired: "الرابط مطلوب",
  invalidParams: "معاملات غير صالحة",
  invalidUrl: "رابط غير صالح",
  noFormats: "لم يُعثر على صيغ قابلة للتحميل.",
  fetchFailed: "تعذّر جلب معلومات الوسائط",
  fetchTimeout: "استغرق التحليل وقتاً طويلاً — حاول مجدداً (قد يكون السيرفر بارداً)",
  missingImageUrl: "رابط الصورة مفقود",
  missingMediaUrl: "رابط الوسائط مفقود",
  imageFetchFailed: "فشل تنزيل الصورة",
  emptyImageResponse: "استجابة فارغة",
  engineInitFailed: "تعذّر تهيئة المحرك",
  privateVideo: "محتوى خاص أو غير متاح.",
  loginRequired: "يتطلب تسجيل دخول على المنصة.",
  facebookRestricted:
    "فيسبوك لا يتيح التحميل من السيرفر لروابط المشاركة. انسخ الرابط من تطبيق فيسبوك (فيديو/reel) أو جرّب منصة أخرى.",
  unsupportedUrl: "رابط غير مدعوم.",
  unreachable: "تعذّر الوصول للمنصة.",
  untitled: "بدون عنوان",
  coverImage: "الغلاف",
  imageN: (n: number) => `صورة ${n}`,
  original: "أصلي",
  videoLabel: "فيديو",
  audioLabel: "صوت",
  imageLabel: "صورة",
  widthPx: (w: number) => `${w} بكسل`,
  heightPx: (h: number) => `${h} بكسل`,
  kbps: (n: number) => `${n} كيلوبت`,
  defaultFilename: "تحميل",
} as const;
